### ISSUE TITLE
How do you run the project? And Error: echodata does not exist

### ISSUE THREAD

**Issue by la122** [mmr12/MGP-AttTCN#1]
Hello,

I think there are some bugs in this repository. I managed to run the project only after changing some code, but still get the error:
Relation "mimic3_mrosnati.echodata« does not exist"

Which operating system and python version do you use?

**Comment by mmr12** [comment]
Hi
I changed the SQL queries so that they don't rely on a schema that you might not have (in this case mimic3_mrosnati) and fixed many errors.
The code should now run with Python 3.8.5, TensorFlow 2.3.0

**Comment by mmr12** [comment]
PS: I haven't updated the readme yet, but you'll have to pass on a string with your postgres login, eg:
`"dbname=mimic user=postgres password=postgres host=localhost options=--search_path=mimiciii"`

**Comment by la122** [comment]
Hi, thank you for the reply and the fixes. I tried it again. Now I am getting some other errors:
## 1
FileNotFoundError: [Errno 2] No such file or directory: '/cluster/home/mrosnat/MGP-AttTCN/data/interim/19-06-12-detailed-case-labels.csv'
### fix
added `-p .` when starting preprocessing

## 2
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'logs/20210312-175605'
### fix
created `logs` folder in project root

## 3
Traceback (most recent call last):
  File ".\src\mains\main.py", line 172, in <module>
    main(
  File ".\src\mains\main.py", line 124, in main
    trainer.run()
  File "C:\Users\Artur\projects\MGP-AttTCN\src\trainers\trainer.py", line 135, in run
    y_true, y_hat, _class = self.dev_eval(dev_batch, step)
  File "C:\Users\Artur\projects\MGP-AttTCN\src\trainers\trainer.py", line 164, in dev_eval
    tf.summary.scalar("loss_dev", loss_dev.numpy(), step=step + dev_batch)
AttributeError: 'NoneType' object has no attribute 'numpy'

Any idea, how to fix the last one?

**Comment by la122** [comment]
Problem 3 seems to be fixed now too but I'm not sure why. I pulled your last changes in the extra_exp branch, reinstalled the requirements and repeated the preprocessing step.

**Comment by yxddzho** [comment]
python scr/data_processing/main.py [-h] -u SQLUSER -pw SQLPASS -ht HOST -db DBNAME -r SCHEMA_READ_NAME [-w SCHEMA_WRITE_NAME] 会报错usage: main.py [-h] [-c CONNECT_KEY] [-p PATH]
main.py: error: argument -h/--help: ignored explicit argument 't'
